# MPG Cars

### Introduction:

The following exercise utilizes data from [UC Irvine Machine Learning Repository](https://archive.ics.uci.edu/ml/datasets/Auto+MPG)

### Step 1. Import the necessary libraries

In [1]:
import numpy as np
import pandas as pd

### Step 2. Import the  datasets [cars1.csv](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/Merge/Auto_MPG/cars1.csv) and [cars2.csv](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/Merge/Auto_MPG/cars2.csv) from the folder

In [6]:
pd.read_csv("C:/Users/user/Desktop/Gurgaon course/Python_homeworks/Pandas Exercises/Pandas Exercises/Exercise Data Files/Pandas Exercise Simple Joins files/cars1.csv")
pd.read_csv("C:/Users/user/Desktop/Gurgaon course/Python_homeworks/Pandas Exercises/Pandas Exercises/Exercise Data Files/Pandas Exercise Simple Joins files/cars2.csv")

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car
0,33.0,4,91,53,1795,17.4,76,3,honda civic
1,20.0,6,225,100,3651,17.7,76,1,dodge aspen se
2,18.0,6,250,78,3574,21.0,76,1,ford granada ghia
3,18.5,6,250,110,3645,16.2,76,1,pontiac ventura sj
4,17.5,6,258,95,3193,17.8,76,1,amc pacer d/l
5,29.5,4,97,71,1825,12.2,76,2,volkswagen rabbit
6,32.0,4,85,70,1990,17.0,76,3,datsun b-210
7,28.0,4,97,75,2155,16.4,76,3,toyota corolla
8,26.5,4,140,72,2565,13.6,76,1,ford pinto
9,20.0,4,130,102,3150,15.7,76,2,volvo 245
10,13.0,8,318,150,3940,13.2,76,1,plymouth volare premier v8
11,19.0,4,120,88,3270,21.9,76,2,peugeot 504
12,19.0,6,156,108,2930,15.5,76,3,toyota mark ii
13,16.5,6,168,120,3820,16.7,76,2,mercedes-benz 280s
14,16.5,8,350,180,4380,12.1,76,1,cadillac seville
15,13.0,8,350,145,4055,12.0,76,1,chevy c10
16,13.0,8,302,130,3870,15.0,76,1,ford f108
17,13.0,8,318,150,3755,14.0,76,1,dodge d100
18,31.5,4,98,68,2045,18.5,77,3,honda accord cvcc
19,30.0,4,111,80,2155,14.8,77,1,buick opel isuzu deluxe
20,36.0,4,79,58,1825,18.6,77,2,renault 5 gtl
21,25.5,4,122,96,2300,15.5,77,1,plymouth arrow gs
22,33.5,4,85,70,1945,16.8,77,3,datsun f-10 hatchback
23,17.5,8,305,145,3880,12.5,77,1,chevrolet caprice classic
24,17.0,8,260,110,4060,19.0,77,1,oldsmobile cutlass supreme
25,15.5,8,318,145,4140,13.7,77,1,dodge monaco brougham
26,15.0,8,302,130,4295,14.9,77,1,mercury cougar brougham
27,17.5,6,250,110,3520,16.4,77,1,chevrolet concours
28,20.5,6,231,105,3425,16.9,77,1,buick skylark
29,19.0,6,225,100,3630,17.7,77,1,plymouth volare custom
...,...,...,...,...,...,...,...,...,...
170,27.0,4,112,88,2640,18.6,82,1,chevrolet cavalier wagon
171,34.0,4,112,88,2395,18.0,82,1,chevrolet cavalier 2-door
172,31.0,4,112,85,2575,16.2,82,1,pontiac j2000 se hatchback
173,29.0,4,135,84,2525,16.0,82,1,dodge aries se
174,27.0,4,151,90,2735,18.0,82,1,pontiac phoenix
175,24.0,4,140,92,2865,16.4,82,1,ford fairmont futura
176,23.0,4,151,?,3035,20.5,82,1,amc concord dl
177,36.0,4,105,74,1980,15.3,82,2,volkswagen rabbit l
178,37.0,4,91,68,2025,18.2,82,3,mazda glc custom l
179,31.0,4,91,68,1970,17.6,82,3,mazda glc custom
180,38.0,4,105,63,2125,14.7,82,1,plymouth horizon miser
181,36.0,4,98,70,2125,17.3,82,1,mercury lynx l
182,36.0,4,120,88,2160,14.5,82,3,nissan stanza xe
183,36.0,4,107,75,2205,14.5,82,3,honda accord
184,34.0,4,108,70,2245,16.9,82,3,toyota corolla
185,38.0,4,91,67,1965,15.0,82,3,honda civic
186,32.0,4,91,67,1965,15.7,82,3,honda civic (auto)
187,38.0,4,91,67,1995,16.2,82,3,datsun 310 gx
188,25.0,6,181,110,2945,16.4,82,1,buick century limited
189,38.0,6,262,85,3015,17.0,82,1,oldsmobile cutlass ciera (diesel)
190,26.0,4,156,92,2585,14.5,82,1,chrysler lebaron medallion
191,22.0,6,232,112,2835,14.7,82,1,ford granada l
192,32.0,4,144,96,2665,13.9,82,3,toyota celica gt
193,36.0,4,135,84,2370,13.0,82,1,dodge charger 2.2
194,27.0,4,151,90,2950,17.3,82,1,chevrolet camaro
195,27.0,4,140,86,2790,15.6,82,1,ford mustang gl
196,44.0,4,97,52,2130,24.6,82,2,vw pickup
197,32.0,4,135,84,2295,11.6,82,1,dodge rampage
198,28.0,4,120,79,2625,18.6,82,1,ford ranger
199,31.0,4,119,82,2720,19.4,82,1,chevy s-10

   ### Step 3. Assign each to a to a variable called cars1 and cars2

In [8]:
cars1=pd.read_csv("C:/Users/user/Desktop/Gurgaon course/Python_homeworks/Pandas Exercises/Pandas Exercises/Exercise Data Files/Pandas Exercise Simple Joins files/cars1.csv")
cars2=pd.read_csv("C:/Users/user/Desktop/Gurgaon course/Python_homeworks/Pandas Exercises/Pandas Exercises/Exercise Data Files/Pandas Exercise Simple Joins files/cars2.csv")
cars1

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu,NaN,NaN,NaN,NaN,NaN
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320,NaN,NaN,NaN,NaN,NaN
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite,NaN,NaN,NaN,NaN,NaN
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst,NaN,NaN,NaN,NaN,NaN
4,17.0,8,302,140,3449,10.5,70,1,ford torino,NaN,NaN,NaN,NaN,NaN
5,15.0,8,429,198,4341,10.0,70,1,ford galaxie 500,NaN,NaN,NaN,NaN,NaN
6,14.0,8,454,220,4354,9.0,70,1,chevrolet impala,NaN,NaN,NaN,NaN,NaN
7,14.0,8,440,215,4312,8.5,70,1,plymouth fury iii,NaN,NaN,NaN,NaN,NaN
8,14.0,8,455,225,4425,10.0,70,1,pontiac catalina,NaN,NaN,NaN,NaN,NaN
9,15.0,8,390,190,3850,8.5,70,1,amc ambassador dpl,NaN,NaN,NaN,NaN,NaN
10,15.0,8,383,170,3563,10.0,70,1,dodge challenger se,NaN,NaN,NaN,NaN,NaN
11,14.0,8,340,160,3609,8.0,70,1,plymouth 'cuda 340,NaN,NaN,NaN,NaN,NaN
12,15.0,8,400,150,3761,9.5,70,1,chevrolet monte carlo,NaN,NaN,NaN,NaN,NaN
13,14.0,8,455,225,3086,10.0,70,1,buick estate wagon (sw),NaN,NaN,NaN,NaN,NaN
14,24.0,4,113,95,2372,15.0,70,3,toyota corona mark ii,NaN,NaN,NaN,NaN,NaN
15,22.0,6,198,95,2833,15.5,70,1,plymouth duster,NaN,NaN,NaN,NaN,NaN
16,18.0,6,199,97,2774,15.5,70,1,amc hornet,NaN,NaN,NaN,NaN,NaN
17,21.0,6,200,85,2587,16.0,70,1,ford maverick,NaN,NaN,NaN,NaN,NaN
18,27.0,4,97,88,2130,14.5,70,3,datsun pl510,NaN,NaN,NaN,NaN,NaN
19,26.0,4,97,46,1835,20.5,70,2,volkswagen 1131 deluxe sedan,NaN,NaN,NaN,NaN,NaN
20,25.0,4,110,87,2672,17.5,70,2,peugeot 504,NaN,NaN,NaN,NaN,NaN
21,24.0,4,107,90,2430,14.5,70,2,audi 100 ls,NaN,NaN,NaN,NaN,NaN
22,25.0,4,104,95,2375,17.5,70,2,saab 99e,NaN,NaN,NaN,NaN,NaN
23,26.0,4,121,113,2234,12.5,70,2,bmw 2002,NaN,NaN,NaN,NaN,NaN
24,21.0,6,199,90,2648,15.0,70,1,amc gremlin,NaN,NaN,NaN,NaN,NaN
25,10.0,8,360,215,4615,14.0,70,1,ford f250,NaN,NaN,NaN,NaN,NaN
26,10.0,8,307,200,4376,15.0,70,1,chevy c20,NaN,NaN,NaN,NaN,NaN
27,11.0,8,318,210,4382,13.5,70,1,dodge d200,NaN,NaN,NaN,NaN,NaN
28,9.0,8,304,193,4732,18.5,70,1,hi 1200d,NaN,NaN,NaN,NaN,NaN
29,27.0,4,97,88,2130,14.5,71,3,datsun pl510,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168,23.0,4,140,83,2639,17.0,75,1,ford pinto,NaN,NaN,NaN,NaN,NaN
169,20.0,6,232,100,2914,16.0,75,1,amc gremlin,NaN,NaN,NaN,NaN,NaN
170,23.0,4,140,78,2592,18.5,75,1,pontiac astro,NaN,NaN,NaN,NaN,NaN
171,24.0,4,134,96,2702,13.5,75,3,toyota corona,NaN,NaN,NaN,NaN,NaN
172,25.0,4,90,71,2223,16.5,75,2,volkswagen dasher,NaN,NaN,NaN,NaN,NaN
173,24.0,4,119,97,2545,17.0,75,3,datsun 710,NaN,NaN,NaN,NaN,NaN
174,18.0,6,171,97,2984,14.5,75,1,ford pinto,NaN,NaN,NaN,NaN,NaN
175,29.0,4,90,70,1937,14.0,75,2,volkswagen rabbit,NaN,NaN,NaN,NaN,NaN
176,19.0,6,232,90,3211,17.0,75,1,amc pacer,NaN,NaN,NaN,NaN,NaN
177,23.0,4,115,95,2694,15.0,75,2,audi 100ls,NaN,NaN,NaN,NaN,NaN
178,23.0,4,120,88,2957,17.0,75,2,peugeot 504,NaN,NaN,NaN,NaN,NaN
179,22.0,4,121,98,2945,14.5,75,2,volvo 244dl,NaN,NaN,NaN,NaN,NaN
180,25.0,4,121,115,2671,13.5,75,2,saab 99le,NaN,NaN,NaN,NaN,NaN
181,33.0,4,91,53,1795,17.5,75,3,honda civic cvcc,NaN,NaN,NaN,NaN,NaN
182,28.0,4,107,86,2464,15.5,76,2,fiat 131,NaN,NaN,NaN,NaN,NaN
183,25.0,4,116,81,2220,16.9,76,2,opel 1900,NaN,NaN,NaN,NaN,NaN
184,25.0,4,140,92,2572,14.9,76,1,capri ii,NaN,NaN,NaN,NaN,NaN
185,26.0,4,98,79,2255,17.7,76,1,dodge colt,NaN,NaN,NaN,NaN,NaN
186,27.0,4,101,83,2202,15.3,76,2,renault 12tl,NaN,NaN,NaN,NaN,NaN
187,17.5,8,305,140,4215,13.0,76,1,chevrolet chevelle malibu classic,NaN,NaN,NaN,NaN,NaN
188,16.0,8,318,150,4190,13.0,76,1,dodge coronet brougham,NaN,NaN,NaN,NaN,NaN
189,15.5,8,304,120,3962,13.9,76,1,amc matador,NaN,NaN,NaN,NaN,NaN
190,14.5,8,351,152,4215,12.8,76,1,ford gran torino,NaN,NaN,NaN,NaN,NaN
191,22.0,6,225,100,3233,15.4,76,1,plymouth valiant,NaN,NaN,NaN,NaN,NaN
192,22.0,6,250,105,3353,14.5,76,1,chevrolet nova,NaN,NaN,NaN,NaN,NaN
193,24.0,6,200,81,3012,17.6,76,1,ford maverick,NaN,NaN,NaN,NaN,NaN
194,22.5,6,232,90,3085,17.6,76,1,amc hornet,NaN,NaN,NaN,NaN,NaN
195,29.0,4,85,52,2035,22.2,76,1,chevrolet chevette,NaN,NaN,NaN,NaN,NaN
196,24.5,4,98,60,2164,22.1,76,1,chevrolet woody,NaN,NaN,NaN,NaN,NaN
197,29.0,4,90,70,1937,14.2,76,2,vw rabbit,NaN,NaN,NaN,NaN,NaN

### Step 4. It seems our first dataset has some unnamed blank columns, fix cars1

In [9]:
cars1=cars1.dropna(axis=1)
cars1

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302,140,3449,10.5,70,1,ford torino
5,15.0,8,429,198,4341,10.0,70,1,ford galaxie 500
6,14.0,8,454,220,4354,9.0,70,1,chevrolet impala
7,14.0,8,440,215,4312,8.5,70,1,plymouth fury iii
8,14.0,8,455,225,4425,10.0,70,1,pontiac catalina
9,15.0,8,390,190,3850,8.5,70,1,amc ambassador dpl
10,15.0,8,383,170,3563,10.0,70,1,dodge challenger se
11,14.0,8,340,160,3609,8.0,70,1,plymouth 'cuda 340
12,15.0,8,400,150,3761,9.5,70,1,chevrolet monte carlo
13,14.0,8,455,225,3086,10.0,70,1,buick estate wagon (sw)
14,24.0,4,113,95,2372,15.0,70,3,toyota corona mark ii
15,22.0,6,198,95,2833,15.5,70,1,plymouth duster
16,18.0,6,199,97,2774,15.5,70,1,amc hornet
17,21.0,6,200,85,2587,16.0,70,1,ford maverick
18,27.0,4,97,88,2130,14.5,70,3,datsun pl510
19,26.0,4,97,46,1835,20.5,70,2,volkswagen 1131 deluxe sedan
20,25.0,4,110,87,2672,17.5,70,2,peugeot 504
21,24.0,4,107,90,2430,14.5,70,2,audi 100 ls
22,25.0,4,104,95,2375,17.5,70,2,saab 99e
23,26.0,4,121,113,2234,12.5,70,2,bmw 2002
24,21.0,6,199,90,2648,15.0,70,1,amc gremlin
25,10.0,8,360,215,4615,14.0,70,1,ford f250
26,10.0,8,307,200,4376,15.0,70,1,chevy c20
27,11.0,8,318,210,4382,13.5,70,1,dodge d200
28,9.0,8,304,193,4732,18.5,70,1,hi 1200d
29,27.0,4,97,88,2130,14.5,71,3,datsun pl510
...,...,...,...,...,...,...,...,...,...
168,23.0,4,140,83,2639,17.0,75,1,ford pinto
169,20.0,6,232,100,2914,16.0,75,1,amc gremlin
170,23.0,4,140,78,2592,18.5,75,1,pontiac astro
171,24.0,4,134,96,2702,13.5,75,3,toyota corona
172,25.0,4,90,71,2223,16.5,75,2,volkswagen dasher
173,24.0,4,119,97,2545,17.0,75,3,datsun 710
174,18.0,6,171,97,2984,14.5,75,1,ford pinto
175,29.0,4,90,70,1937,14.0,75,2,volkswagen rabbit
176,19.0,6,232,90,3211,17.0,75,1,amc pacer
177,23.0,4,115,95,2694,15.0,75,2,audi 100ls
178,23.0,4,120,88,2957,17.0,75,2,peugeot 504
179,22.0,4,121,98,2945,14.5,75,2,volvo 244dl
180,25.0,4,121,115,2671,13.5,75,2,saab 99le
181,33.0,4,91,53,1795,17.5,75,3,honda civic cvcc
182,28.0,4,107,86,2464,15.5,76,2,fiat 131
183,25.0,4,116,81,2220,16.9,76,2,opel 1900
184,25.0,4,140,92,2572,14.9,76,1,capri ii
185,26.0,4,98,79,2255,17.7,76,1,dodge colt
186,27.0,4,101,83,2202,15.3,76,2,renault 12tl
187,17.5,8,305,140,4215,13.0,76,1,chevrolet chevelle malibu classic
188,16.0,8,318,150,4190,13.0,76,1,dodge coronet brougham
189,15.5,8,304,120,3962,13.9,76,1,amc matador
190,14.5,8,351,152,4215,12.8,76,1,ford gran torino
191,22.0,6,225,100,3233,15.4,76,1,plymouth valiant
192,22.0,6,250,105,3353,14.5,76,1,chevrolet nova
193,24.0,6,200,81,3012,17.6,76,1,ford maverick
194,22.5,6,232,90,3085,17.6,76,1,amc hornet
195,29.0,4,85,52,2035,22.2,76,1,chevrolet chevette
196,24.5,4,98,60,2164,22.1,76,1,chevrolet woody
197,29.0,4,90,70,1937,14.2,76,2,vw rabbit

### Step 5. What is the number of observations in each dataset?

In [10]:
x=cars1.count(axis=0)
y=cars2.count(axis=0)
print(x)
print(y)

mpg             198
cylinders       198
displacement    198
horsepower      198
weight          198
acceleration    198
model           198
origin          198
car             198
dtype: int64
mpg             200
cylinders       200
displacement    200
horsepower      200
weight          200
acceleration    200
model           200
origin          200
car             200
dtype: int64

### Step 6. Join cars1 and cars2 into a single DataFrame called cars

In [13]:
cars=pd.concat([cars1,cars2])
cars
cars.shape[0]

398

### Step 7. There is a column missing, called owners. Create a random number Series from 15,000 to 73,000.

In [11]:
owners=pd.Series(np.random.randint(15000,73000,398))
owners

0      28163
1      29688
2      21233
3      21146
4      65997
5      22347
6      54489
7      37079
8      36513
9      31512
10     38007
11     51176
12     20766
13     69234
14     68243
15     19056
16     63740
17     35318
18     57747
19     68527
20     57199
21     24142
22     55726
23     36491
24     58834
25     29922
26     49877
27     19134
28     55558
29     47647
       ...
368    24317
369    31773
370    22099
371    43464
372    71190
373    30621
374    45150
375    57302
376    52735
377    61832
378    41304
379    46684
380    30437
381    59265
382    40584
383    29475
384    26703
385    69460
386    44536
387    52194
388    45536
389    46155
390    44160
391    43570
392    33017
393    64267
394    15535
395    68610
396    51771
397    61236
Length: 398, dtype: int32

### Step 8. Add the column owners to cars

In [14]:
cars["owners"]=owners

In [40]:
cars

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car,owners
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu,51114
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320,17806
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite,39482
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst,53752
4,17.0,8,302,140,3449,10.5,70,1,ford torino,66544
5,15.0,8,429,198,4341,10.0,70,1,ford galaxie 500,51443
6,14.0,8,454,220,4354,9.0,70,1,chevrolet impala,21134
7,14.0,8,440,215,4312,8.5,70,1,plymouth fury iii,56270
8,14.0,8,455,225,4425,10.0,70,1,pontiac catalina,66685
9,15.0,8,390,190,3850,8.5,70,1,amc ambassador dpl,54885
10,15.0,8,383,170,3563,10.0,70,1,dodge challenger se,36067
11,14.0,8,340,160,3609,8.0,70,1,plymouth 'cuda 340,35687
12,15.0,8,400,150,3761,9.5,70,1,chevrolet monte carlo,67238
13,14.0,8,455,225,3086,10.0,70,1,buick estate wagon (sw),52441
14,24.0,4,113,95,2372,15.0,70,3,toyota corona mark ii,60168
15,22.0,6,198,95,2833,15.5,70,1,plymouth duster,45916
16,18.0,6,199,97,2774,15.5,70,1,amc hornet,25354
17,21.0,6,200,85,2587,16.0,70,1,ford maverick,38315
18,27.0,4,97,88,2130,14.5,70,3,datsun pl510,68471
19,26.0,4,97,46,1835,20.5,70,2,volkswagen 1131 deluxe sedan,23855
20,25.0,4,110,87,2672,17.5,70,2,peugeot 504,38931
21,24.0,4,107,90,2430,14.5,70,2,audi 100 ls,16541
22,25.0,4,104,95,2375,17.5,70,2,saab 99e,58036
23,26.0,4,121,113,2234,12.5,70,2,bmw 2002,24532
24,21.0,6,199,90,2648,15.0,70,1,amc gremlin,61615
25,10.0,8,360,215,4615,14.0,70,1,ford f250,28025
26,10.0,8,307,200,4376,15.0,70,1,chevy c20,34500
27,11.0,8,318,210,4382,13.5,70,1,dodge d200,23437
28,9.0,8,304,193,4732,18.5,70,1,hi 1200d,68132
29,27.0,4,97,88,2130,14.5,71,3,datsun pl510,39337
...,...,...,...,...,...,...,...,...,...,...
170,27.0,4,112,88,2640,18.6,82,1,chevrolet cavalier wagon,31311
171,34.0,4,112,88,2395,18.0,82,1,chevrolet cavalier 2-door,52959
172,31.0,4,112,85,2575,16.2,82,1,pontiac j2000 se hatchback,35342
173,29.0,4,135,84,2525,16.0,82,1,dodge aries se,18615
174,27.0,4,151,90,2735,18.0,82,1,pontiac phoenix,48222
175,24.0,4,140,92,2865,16.4,82,1,ford fairmont futura,69260
176,23.0,4,151,?,3035,20.5,82,1,amc concord dl,50520
177,36.0,4,105,74,1980,15.3,82,2,volkswagen rabbit l,39717
178,37.0,4,91,68,2025,18.2,82,3,mazda glc custom l,45294
179,31.0,4,91,68,1970,17.6,82,3,mazda glc custom,32950
180,38.0,4,105,63,2125,14.7,82,1,plymouth horizon miser,45592
181,36.0,4,98,70,2125,17.3,82,1,mercury lynx l,66929
182,36.0,4,120,88,2160,14.5,82,3,nissan stanza xe,27501
183,36.0,4,107,75,2205,14.5,82,3,honda accord,25458
184,34.0,4,108,70,2245,16.9,82,3,toyota corolla,24683
185,38.0,4,91,67,1965,15.0,82,3,honda civic,26893
186,32.0,4,91,67,1965,15.7,82,3,honda civic (auto),51416
187,38.0,4,91,67,1995,16.2,82,3,datsun 310 gx,64983
188,25.0,6,181,110,2945,16.4,82,1,buick century limited,64235
189,38.0,6,262,85,3015,17.0,82,1,oldsmobile cutlass ciera (diesel),49057
190,26.0,4,156,92,2585,14.5,82,1,chrysler lebaron medallion,34656
191,22.0,6,232,112,2835,14.7,82,1,ford granada l,37420
192,32.0,4,144,96,2665,13.9,82,3,toyota celica gt,36791
193,36.0,4,135,84,2370,13.0,82,1,dodge charger 2.2,27019
194,27.0,4,151,90,2950,17.3,82,1,chevrolet camaro,48376
195,27.0,4,140,86,2790,15.6,82,1,ford mustang gl,69652
196,44.0,4,97,52,2130,24.6,82,2,vw pickup,57456
197,32.0,4,135,84,2295,11.6,82,1,dodge rampage,18272
198,28.0,4,120,79,2625,18.6,82,1,ford ranger,54458
199,31.0,4,119,82,2720,19.4,82,1,chevy s-10,41036